[package]
name = "suru-lang-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
